language: python
python: 3.8
before_install:
- sudo apt-get update -q && sudo apt-get install nodejs -yqq
- sudo apt-get install libpq-dev -yqq
- python -V
install:
- pip install -r requirements.txt
script:
- npm install -g snyk
- snyk auth $SNYK_TOKEN
- snyk test
- git init
# - git add .
# - git commit -m "Auto push"
- git remote add lab https://l-bot:1yfM4rwxUz4kx5szA6yV@gitlab.com/gamer4life1/second-django-app.git
- git push lab master
