language: python
python: 3.8
before_install:
- sudo apt-get update -q && sudo apt-get install nodejs -yqq
- sudo apt-get install libpq-dev -yqq
- python -V
install:
- pip install -r requirements.txt
script:
- npm install -g snyk
- snyk auth $SNYK_TOKEN
- snyk test
- git remote add lab https://gamer4life1:$(GITLAB_TOKEN)@gitlab.com/gamer4life1/second-django-app.git
- git push lab master
env:
  global:
  - secure: ohijMS+nZr6XyOpCZQsvEswYRfgVvg+WgLs9y4BuYWOyvc6yZT5wXkNeiSfIDYIa1z16jEbcLGlCQCc4SWiusv6yb9zif7d0fV5gjSSnDSxvn8CAAxWnDMEF84DdeCIYMAusT5pKpZGEopKNYffa4BEWUm6XinAIf/F7J2jQ2k0Y1F5zV0sv2isUgrtX1t3JaAuXLGWHT0NowG/y0w7Vfoc5M2GeMT2/I1kd4BY8ocT6J7BtW3AenyjV58zV0ffyqXTJXLNny+NG1CzaSd6GlOPtph30NjJZQfpY45Dh07hqC+yKD80raAdSLcCdIi7yDOqEwnqSxcrqFZuMmIXySORpZmshmS5A3GL/kO0uD2Q1FTlitCP+xX8u/B/4g5wJDeDM4feNI4aomReeo69oLz5y+KKCs6/adBB7tidOl2LbdQ6cdAlzNC/+KgR77jaxcxvydj1k6R8i+wNMOntlviEguqwhsofNiwyydHM82LrgX7XJpywHdORRgAdEMumnqbtkXpiSlUvKI9IJz5AGZudjJWAPCWfhF+Fpsdel9cGgCXT/JmVXITJRHz13vJa0wM1Szd6ymYpT2xZmV/0VhBSeQ+dwM8x9w9JLjqSxGX04uPcyNZIplvdQQ0ZDyWrOk2VtnHGywG2Zo241RxFWs5PNb/n4TOpwGMi9apw+5iY=
  - secure: TWg7N7YdUZ9JEPNAhH/oxnY6ZrbwqDJhZ9TY8qPGuxAN4E/QHyehNZ5Iz5Zik8M3Z6u81dgom088O6yQTP4RWdgJ1GLDTFLOmR3zAMzMB0YhTvwbMwb0hGqYYKYU9aS7vYlDK5PlgHpn9i8sVB5zjFzACTl1ZOJ0BX7xWX1LHIZtra1sp08HmHypRrc4ysH8iYSJdDAl4uP0mU9V1OSjEMnjrzFW4GBLrDu3N1zYHwQNzNJtBWYDkjnuEeWo8oXvwwmboM+TL5+6dBY7EbcAGWwHq14B2SFvH9JhUNCplqeuDsmCRsVrX/vNoNUmgyqqTBVco+n+pRMvFbGyW1JOFHGaSvARv4VXmVrXXkXPLPYq0/7zTMgXxVoXQHKyOtUtCxRDdaZzBrGhjoEKUxsaPlBvOmDmO6YeNiVnvE+Ma58u6jJcW4DohmoJcJkG4retBImQhJAVqNpsHT1Zleu+UkI6uoM5/GeoW69+Eo7/CxOFaB0qprrTqQ48PINYiP3LMa3Vx6eeJdivAr5uxncck4J7Cya09jOAXpAoA/g81A3D9ZBO4LCDxNGsMKt3d9pEMz4cboLoVsvqJa5uz0mUUOmluMw63fxOXp+cUrQMI2U2VFa9mI7M3yABIkjudS7Dk50xVY9GMLdsKKnZpd1JS7oFE7tqpBq45MxnHeZd/ug=
