name: Caching Dependencies

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: Cache Deps
      id: cache-deps
      uses: actions/cache@v1
      with:
        path: deps
        key: ${{ runner.os }}-deps
